version: "3.8"

services:
  localstack:
    container_name: localstack_mlops
    image: localstack/localstack-pro:latest
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - SERVICES=s3,glue,iam,lambda,sagemaker,cloudwatch,sns,sqs,stepfunctions,events
      - DEBUG=0
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
    volumes:
      - "./terraform:/etc/localstack/init/ready.d"  
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      # 👇 AGREGA ESTA LÍNEA PARA INYECTAR TUS CREDENCIALES DE AWS 👇
      - "~/.docker/config.json:/root/.docker/config.json:ro"